<a href="https://colab.research.google.com/github/nithyashree66/Python/blob/main/linear_algebra_and_statistical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MATH FUNCTIONS USING NUMPY LIBRARY**

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,9,8,7,6],[5,4,3,2,1]])

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

**MATRIX OPERATION**

In [ ]:
#respective elements of RxC will be added
print(arr1+arr2)

[[11 11 11 11 11]
 [11 11 11 11 11]]


In [ ]:
#ADDING an element with the matrix
print(arr1+20)

[[21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
arr3 = np.array([1,2])
print(arr1+arr3)

ValueError: ignored

**arr3 is one dimensional matrix. therefore its shape will have only one axis.and since it does not have 5 elements in the row, it cannot be added to arr1.**

In [ ]:
arr3 = ([1,2,3,4,5])
print(arr1+arr3)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [ ]:
#subtracting two matrices
print(arr1-arr2)

[[-9 -7 -5 -3 -1]
 [ 1  3  5  7  9]]


In [ ]:
#subtracting a matrix with an element
arr1-100

array([[-99, -98, -97, -96, -95],
       [-94, -93, -92, -91, -90]])

In [ ]:
#DIVISION
print(arr1/arr2)

[[ 0.1         0.22222222  0.375       0.57142857  0.83333333]
 [ 1.2         1.75        2.66666667  4.5        10.        ]]


In [ ]:
print(arr1/4)

[[0.25 0.5  0.75 1.   1.25]
 [1.5  1.75 2.   2.25 2.5 ]]


In [ ]:
#EXPONENT - elements in arr1 will be raised to the power of respective indeces in arr2
arr1**arr2

array([[    1,   512,  6561, 16384, 15625],
       [ 7776,  2401,   512,    81,    10]])

In [ ]:
print(arr1**2)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [ ]:
#MULTIPLICATION - CROSS PRODUCT
arr1 * arr2

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [ ]:
#MULTIPLICATION - DOT PRODUCT
a=([[1,2,3],[3,2,1]])
b=([[1,2],[3,2],[2,7]])
c=np.dot(a,b)
print(c)

[[13 27]
 [11 17]]


In [ ]:
c=np.dot(b,a)
print(c)

[[ 7  6  5]
 [ 9 10 11]
 [23 18 13]]


In [ ]:
# matmul(), dot() are just semantics
c=np.matmul(a,b)
print(c)

[[13 27]
 [11 17]]


In [ ]:
#DETERMINANT
det = np.array([[-4,-10],[0,5]])
print(det)

[[ -4 -10]
 [  0   5]]


**difference between matix and determinant is that, determinants must have equal no.of rows and columns (square matrix) but matrices can have unequal or equal number of columns and rows**

In [ ]:
#finding the determinant of an array
det1 =([[-4,-10,-6],[0,5,7],[-9,6,0]])
determinant = np.linalg.det(det1)
print(determinant)

528.0


In [ ]:
a = [a1 a2 a3]
    [b1 b2 b3]
    [c1 c2 c3]

det(a) = a1[b2 b3] - a2[b1 b3] + a3[b1 b2]
           [c2 c3]     [c1 c3]     [c1 c2]

        = a1(b2c3-b3c2) -a2(b1c3-b3c1) + a3(b1c2-b2c1)

        

SyntaxError: ignored

**inverse of a matrix**

In [ ]:
inverse = np.array([[1,2],[3,4]])
print(inverse)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(inverse)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#adjoint of the matrix - find the transpose matrix

In [ ]:
inverse.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
#RECIPROCAL - reciprocal of every element is returned as a result.
reci = np.array([[10.1,20.2],[30.3,40.4]])
np.reciprocal(reci)

array([[0.0990099 , 0.04950495],
       [0.0330033 , 0.02475248]])

In [ ]:
arr = np.array([[20,-9,-40],[0,10,-1],[7,6,34]])

In [ ]:
print(arr)

[[ 20  -9 -40]
 [  0  10  -1]
 [  7   6  34]]


In [ ]:
# MAX()
print(np.max(arr)) #returns the biggest element in the array

34


In [ ]:
np.max(arr, axis = 0) # 0th axis means column. so find the max in each column

array([20, 10, 34])

In [ ]:
np.max(arr, axis = 1)

array([20, 10, 34])

In [ ]:
arr = np.array([[20,50,-40],[9,10,-1],[7,26,34]])
print(arr)

[[ 20  50 -40]
 [  9  10  -1]
 [  7  26  34]]


In [ ]:
np.max(arr,axis =1) #max , row-wise

array([50, 10, 34])

In [ ]:
#MIN()
np.min(arr)

-40

In [ ]:
np.min(arr, axis=0)

array([  7,  10, -40])

In [ ]:
np.min(arr, axis =1)

array([-40,  -1,   7])

In [ ]:
np.min(arr,axis = 2)

AxisError: ignored

**since arr is a 2 dimensional array, it has only two axis. so, axis= 2 points to the 3rd dimension. therefore we get error.**

In [ ]:
arr

array([0.56, 0.98])

In [ ]:
#sum of all the elements in an array , column-wise
np.sum(arr) 

115

In [ ]:
#since axis=0 is column-wise, the sum of individual columns will be returned in the form of an array
np.sum(arr,axis = 0)

array([36, 86, -7])

In [ ]:
np.sum(arr,axis=1)

array([30, 18, 67])

In [ ]:
#argmax() returns the index of the largest element in the matrix
np.argmax(arr)

1

In [ ]:
#argmin() returns the index of the smallest element in the matrix
np.argmin(arr)

2

In [ ]:
np.argmax(arr, axis =0)

array([0, 0, 2])

In [ ]:
np.argmax(arr,axis =1)

array([1, 1, 2])

In [ ]:
np.argmin(arr,axis=0)

array([2, 1, 0])

In [ ]:
np.argmin(arr,axis =1)

array([2, 2, 0])

In [ ]:
#around() - evenly rounds off the number to its nearest number

In [ ]:
arr=np.array([0.56,0.98])

In [ ]:
np.around(arr)

array([1., 1.])

In [ ]:
#example 2
arr1 = np.array([3.501,0.98])
print(arr1)

[3.501 0.98 ]


In [ ]:
np.around(arr1)

array([4., 1.])

In [ ]:
#floor() - returns the (lower)floor value of a number
np.floor(arr1)

array([3., 0.])

In [ ]:
#ceil() -rounds off the value of integer to a slightly greater number
np.ceil(arr1)

array([4., 1.])

**COPY AND VIEW
the matrix is copied and any changes made to the duplicate matrix will not affect the original matrix and vice versa.**

In [ ]:
print("orginal matrix ",arr)
x = arr.copy()
print("copy matrix ",x)

orginal matrix  [0.56 0.98]
copy matrix  [0.56 0.98]


In [ ]:
x[0]= 78.9

In [ ]:
print("copy matrix ",x)

copy matrix  [78.9   0.98]


In [ ]:
print(arr)

[0.56 0.98]


**it is clearly seen here that the changes made to the copy matrix does not affect the original matrix**

In [ ]:
x= arr.view()
print("view array: ",x)

view array:  [0.56 0.98]


In [ ]:
x[0]= 90.8
print("changed view array: ",x)

changed view array:  [90.8   0.98]


In [ ]:
print("original: ",arr)
print("view: ",x)

original:  [90.8   0.98]
view:  [90.8   0.98]


**the view() function creates a copy of original matrix and any changes made in the copy will affect the original matrix**

In [ ]:
for i in arr:
  print(i)

0.56
0.98


**if there are n elements , then with each increase in number, the complexity increases.**

In [ ]:
arr = np.array([[20,50,-40],[9,10,-1],[7,26,34]])

In [ ]:
for i in np.nditer(arr[1])

SyntaxError: ignored