<a href="https://colab.research.google.com/github/nithyashree66/Python/blob/main/NumPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**numpy abreviated as numerical python is a library of mathematical functions used in computation.<br>
numpy is faster because it uses less memory and it has contiguous memory that stores homogeneous data unlike lists.<br>**

In [1]:
import numpy as np

**CREATE**

In [ ]:
#one dimensional array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#two dimensional array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#three dimensional array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]],[[6,5,4],[3,2,1]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]

 [[6 5 4]
  [3 2 1]]]


In [ ]:
#check number of dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
#check the datatype of array
a.dtype

dtype('int64')

In [ ]:
#get the size
c.itemsize

8

In [ ]:
#to get an element , we specify the row and column number
c[2,1]

array([3, 2, 1])

In [ ]:
#to get the diagonal matrix
arr = np.diag([10,20,30,40])
print(arr)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [ ]:
#creating random array within a specified range using linspace()
arr = np.linspace(0,10,20) #creating array of numbers between 0-10 with 20 values in between.
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [ ]:
#random values with a specified range
arr = np.random.rand(10)
print(arr)

[0.02160482 0.42567922 0.61648668 0.34860571 0.3486839  0.72501754
 0.30056398 0.01600905 0.47265341 0.76245199]


In [ ]:
#numbers within a specified range. (start,stop,step).
arr = np.arange(45,98)
print(arr)
#the last value will not be included.

[45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68
 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92
 93 94 95 96 97]


**UPDATE**

In [ ]:
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#accessing elements using index
b[2,2]

1

In [ ]:
#changing elements at a specified index
b[2,2] = 50
print(b)

[[ 9  8  7]
 [ 6  5  4]
 [ 3  2 50]]


In [ ]:
#slicing
b[2:]

array([[ 3,  2, 50]])

In [ ]:
b[0,1:10]

array([8, 7])

In [ ]:
#every element with a step of 2
b[::2]

array([[ 9,  8,  7],
       [ 3,  2, 50]])

**random.rand(x,y) creates a RANDOM ARRAY of specified dimension with random values in it.**

In [2]:
data1 = np.random.rand(10,3) #random.rand(10 rows, 3 columns)

In [3]:
data1

array([[0.57283378, 0.02024448, 0.76381467],
       [0.47879355, 0.21451669, 0.14456568],
       [0.0677984 , 0.71582508, 0.25695949],
       [0.90130836, 0.46621277, 0.21040897],
       [0.01240322, 0.30779622, 0.37048014],
       [0.5627291 , 0.16602479, 0.72367035],
       [0.64721344, 0.16122331, 0.99564031],
       [0.07716572, 0.99795373, 0.80334255],
       [0.21377439, 0.0448266 , 0.89738359],
       [0.61331266, 0.17377175, 0.30357353]])